[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "focustuner"
version = "0.1.0"
authors = [
  { name="Grace Gomez", email="grace.gomez@colorado.edu" },
]
description = "Python Instrument Control for Focus Mechanical Load tuner CCMT 1808"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/RFPAL-Github-Organization/LoadTuner-repo"

[build-system]
requires = [
  "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"