function freq1 = importAttenFreq(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FREQ1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  FREQ1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  freq1 = importfile("C:\Users\Batman 2.0\Documents\Research\NG90nm_LMBA\testData\outAtten_20240228_test2\freq1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Feb-2024 13:12:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
freq1 = readtable(filename, opts);

%% Convert to output type
freq1 = table2array(freq1);
end